# Generated by Django 5.2.5 on 2025-09-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=255)),
                ('action', models.TextField()),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Error', 'Error'), ('Info', 'Info'), ('Warning', 'Warning')], max_length=10)),
                ('ipAddress', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
