# Generated by Django 5.2.5 on 2025-09-23 07:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemAlerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemalert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='systemalert',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemalert',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
